inmobiliaria_priego_inmuebles_homepage:
    path:     /
    defaults: { _controller: InmobiliariaPriegoInmueblesBundle:Default:index }

inmobiliaria_priego_inmuebles_sheet:
    path:     /inmuebles/{ref}
    defaults: { _controller: InmobiliariaPriegoInmueblesBundle:Default:sheet }