inmobiliaria_priego_inmuebles_inmueble:
    resource: "@InmobiliariaPriegoInmueblesBundle/Resources/config/routing/inmueble.yml"
    prefix:   /inmueble

inmobiliaria_priego_inmuebles_homepage:
    path:     /
    defaults: { _controller: InmobiliariaPriegoInmueblesBundle:Default:index }

inmobiliaria_priego_inmuebles_sheet:
    path:     /inmuebles/{ref}
    defaults: { _controller: InmobiliariaPriegoInmueblesBundle:Default:sheet }
    
inmobiliaria_priego_inmuebles_create:
    pattern: /inmueble/create
    defaults: { _controller: InmobiliariaPriegoInmueblesBundle:Inmueble:create }