inmobiliaria_priego_usuarios:
    resource: "@InmobiliariaPriegoUsuariosBundle/Resources/config/routing.yml"
    prefix:   /

inmobiliaria_priego_inmuebles:
    resource: "@InmobiliariaPriegoInmueblesBundle/Resources/config/routing.yml"
    prefix:   /

inmobiliaria_priego_web:
    resource: "@InmobiliariaPriegoWebBundle/Resources/config/routing.yml"
    prefix:   /

inmobiliaria_priego_buscador:
    resource: "@InmobiliariaPriegoBuscadorBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
