# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

# Código inicial de la aplicación

#security:    
    
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    #providers:
    #    in_memory:
    #        memory: ~

    #firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        #dev:
            #pattern: ^/(_(profiler|wdt)|css|images|js)/
            #security: false

        #main:
            #anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

# Código de Rubén

security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        InmobiliariaPriego\UsuariosBundle\Entity\Usuario:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
            
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        #in_memory:
        #    memory:
        #        users:
        #            user: { password: user, roles: ROLE_USER }
        #            admin: { password: admin, roles: ROLE_ADMIN }
        users:
            entity: { class: InmobiliariaPriegoUsuariosBundle:Usuario, property: userid }
            
    firewalls:
        login_firewall:
                pattern: ^/login$
                anonymous: ~
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                    login_path: login
                    check_path: login_check
            # Para auntenticación http
            #http_basic:
            #    realm: "Mis Inmuebles"
            logout: ~
                #path: /logout
                #target: /
                    
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/create, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST, PUT] }
        - { path: ^/usuario, roles: ROLE_ADMIN }