services:
#    inmobiliaria_priego_usuarios.example:
#        class: InmobiliariaPriego\UsuariosBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    usuario.findbyid:
        class: InmobiliariaPriego\UsuariosBundle\Model\obtenerUsuario
        arguments: ["@doctrine.orm.entity_manager"]