InmobiliariaPriego\UsuariosBundle\Entity\Usuario:
    properties:
        userid:
            - NotBlank: ~
            
        password:
            - NotBlank: ~
            
        username:
            - NotBlank: ~
            
    getters:
        valid:
            - "True": { message: "Mensaje desde validador" }