InmobiliariaPriego\InmueblesBundle\Entity\Inmueble:
    type: entity
    table: inmueble
    id:
        ref:
            type: integer
    fields:
        tipo:
            type: string
            length: 255
        descripcion:
            type: string
            length: 1000
        zona:
            type: string
            length: 255
        planta:
            type: string
            length: 255
        calle:
            type: string
            length: 255
        poblacion:
            type: string
            length: 255
        provincia:
            type: string
            length: 255
        pais:
            type: string
            length: 255
        terraza:
            type: boolean
        metrosterraza:
            type: decimal
            scale: 2
        jardin:
            type: boolean
        metrosjardin:
            type: decimal
            scale: 2
        habitacionesdobles:
            type: integer
        habitacionessimples:
            type: integer
        banyos:
            type: integer
        superficie:
            type: decimal
            scale: 2
        ascensor:
            type: boolean
        garaje:
            type: boolean
        trastero:
            type: boolean
        metrostrastero:
            type: decimal
            scale: 2
        obranueva:
            type: boolean
        operacion:
            type: string
            length: 255
        precio:
            type: decimal
            scale: 2
        img:
            type: string
            length: 255
        destacado:
            type: boolean
            