InmobiliariaPriego\UsuariosBundle\Entity\Usuario:
    type: entity
    table: usuario
    id:
        userid:
            type: string
            length: 255
    fields:
        password:
            type: string
            length: 255
        username:
            type: string
            length: 255
        salt:
            type: string
            length: 64
        roles:
            type: string
            length: 255
        
    lifecycleCallbacks: { }
            